//! Burn autograd fuzz

//! input: AutogradProgram AST generated by arbitrary
//! env config: MAX_LEAVES (default 4), MODE (default panic),
//!             BACKENDS (default: all compiled in, reference side first)

#![no_main]

use fuzzburn::ir::{interpreter, program::AutogradProgram, FuzzConfig, HarnessMode};
use libfuzzer_sys::fuzz_target;

fuzz_target!(|prog: AutogradProgram| {
    let config = FuzzConfig::from_env();
    if prog.ops.len() < config.min_ops { return; }
    if let Err(msg) = interpreter::run_autograd_program(&prog, &config) {
        let display = prog.ssa(config.max_leaves);
        match config.mode {
            HarnessMode::PanicOnFirstError => {
                panic!("fuzz_autograd CRASH:\n{display}\nerror: {msg}");
            }
            HarnessMode::Continuous => {
                eprintln!("\n=== CRASH (fuzz_autograd, continuing) ===\n{display}\nerror: {msg}\n");
            }
        }
    }
});
